def Play_Happy_Xmas():
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.WHOLE))
    music.play_tone(294, music.beat(BeatFraction.WHOLE))
    music.play_tone(294, music.beat(BeatFraction.WHOLE))
    music.play_tone(294, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(466, music.beat(BeatFraction.WHOLE))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.play_tone(294, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.WHOLE))
    music.play_tone(294, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.play_tone(294, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
def No_Bauble():
    led.plot_brightness(1, 2, Low)
    led.plot_brightness(3, 2, Low)
    led.plot_brightness(0, 3, Low)
    led.plot_brightness(4, 3, Low)
def All_Off():
    No_Bauble()
    basic.pause(100)
    No_Star()
def tree2():
    led.plot_brightness(2, 0, Low)
    led.plot_brightness(1, 1, Low)
    led.plot_brightness(2, 1, Low)
    led.plot_brightness(3, 1, Low)
    led.plot_brightness(1, 2, Low)
    led.plot_brightness(2, 2, Low)
    led.plot_brightness(3, 2, Low)
    led.plot_brightness(4, 2, Low)
    led.plot_brightness(0, 2, Low)
    led.plot_brightness(0, 3, Low)
    led.plot_brightness(4, 3, Low)
    led.plot_brightness(1, 3, Low)
    led.plot_brightness(2, 3, Low)
    led.plot_brightness(3, 3, Low)
    led.plot_brightness(2, 4, Low)
def on_button_pressed_a():
    All_On()
input.on_button_pressed(Button.A, on_button_pressed_a)
def Star():
    led.plot_brightness(2, 0, 255)
def on_button_pressed_b():
    All_Off()
input.on_button_pressed(Button.B, on_button_pressed_b)
def Draw_Tree_1():
    led.plot_brightness(2, 0, 0)
    led.plot_brightness(2, 1, Low)
    led.plot_brightness(1, 2, Low)
    led.plot_brightness(2, 2, Low)
    led.plot_brightness(3, 2, Low)
    led.plot_brightness(0, 3, Low)
    led.plot_brightness(1, 3, Low)
    led.plot_brightness(2, 3, Low)
    led.plot_brightness(3, 3, Low)
    led.plot_brightness(4, 3, Low)
    led.plot_brightness(2, 4, Low)
def Bauble_on():
    led.plot_brightness(1, 2, 255)
    led.plot_brightness(3, 2, 255)
    led.plot_brightness(0, 3, 255)
    led.plot_brightness(4, 3, 255)
def All_On():
    Star()
    Bauble_on()
def No_Star():
    led.plot_brightness(2, 0, 0)
Low = 0
Low = 32
Draw_Tree_1()
music.set_tempo(260)
def on_forever():
    All_Off()
    for index in range(4):
        Star()
        basic.pause(200)
        No_Star()
        basic.pause(500)
    for index2 in range(4):
        Bauble_on()
        basic.pause(200)
        No_Bauble()
        basic.pause(500)
    for index3 in range(4):
        All_On()
        basic.pause(500)
        All_Off()
        basic.pause(1000)
    All_On()
    Play_Happy_Xmas()
basic.forever(on_forever)